export const SET_TRANSFORMERS = 'SET_TRANSFORMERS';
export const FETCH_TRANSFORMERS_FAILED = 'FETCH_TRANSFORMERS_FAILED';
export const TRANSFORMERS_LOADING = 'TRANSFORMERS_LOADING';

export const DATA_PROCESSING = 'DATA_PROCESSING';
export const DATA_PROCESS_FAILED = 'DATA_PROCESS_FAILED';
export const SET_UPDATEDITEM = 'SET_UPDATEDITEM';
export const SET_REMOVEITEM = 'SET_REMOVEITEM';
export const ADD_NEWITEM = 'ADD_NEWITEM';

export const SET_BATTLEPROCESSING = 'SET_BATTLEPROCESSING';
export const SET_BATTLERESULT = 'SET_BATTLERESULT';